name: Build, test and deliver container

on:
  push:
      branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java 11 build, test, deliver container
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Start PostgreSQL for integration test
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
          postgresql db: 'weapon'
          postgresql user: 'postgres'
          postgresql password: '1234'
          
      - name: Build, test and package project
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=SybrenVanGastel_weapon-service

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/apt-weapon-service:latest .

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/apt-weapon-service:latest
